version: "3.3"
services:
  web:
    build: ./docker.config/web/.
    ports:
      - 8000:8000
    volumes:
      - ./:/home/work/rust-rocket-web
      - web_cargo_volumn:/usr/local/cargo
    depends_on:
      - mysql_db
    tty: true

  mysql_db:
    image: mysql:5.7
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  db_volume:
  web_cargo_volumn:
